name: CI

on:
  push:
    branches: [$default-branch, 'develop']
  pull_request:
    branches: [$default-branch, 'develop']

jobs:
  lint:
    name: â¬£ ESLint via Node ${{ matrix.node-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: â” Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¥ Download Dependencies
        uses: bahmutov/npm-install@v1

      - name: ğŸ”¬ Lint
        run: yarn lint

  typecheck:
    name: Ê¦ TypeScript via Node ${{ matrix.node-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: â” Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¥ Download Dependencies
        uses: bahmutov/npm-install@v1

      - name: ğŸ” Type check
        run: yarn typecheck

  vitest:
    name: âš¡ Vitest via Node ${{ matrix.node-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: â” Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¥ Download Dependencies
        uses: bahmutov/npm-install@v1

      - name: âš¡ Run Vitest
        run: yarn test:ci

      - name: âš¡ Run Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: ğŸ§± Build via Node ${{ matrix.node-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: â” Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¥ Download Dependencies
        uses: bahmutov/npm-install@v1
        with:
          NODE_ENV: production
          useLockFile: false

      - name: ğŸ§± Run Build
        run: yarn build

